name: Rust Build

on:
  push:
    branches: [ master ]
jobs:
  plugin:
    runs-on: ubuntu-latest
    container: jugeeya/cargo-skyline:latest
    env:
      PLUGIN_NAME: 'libparam_hook.nro'  #  change this to the name of your plugin
    steps:
    - name: Clone master
      run: git clone https://github.com/ultimate-research/param-hook-plugin
      working-directory: /volume/
    - name: Build release NRO
      run: cargo skyline build --release
      working-directory: /volume/param-hook-plugin
    - name: Upload plugin artifact
      uses: actions/upload-artifact@v2
      with:
        name: plugin
        path: /volume/param-hook-plugin/target/aarch64-skyline-switch/release/${{env.PLUGIN_NAME}}
  upload:
    runs-on: ubuntu-latest
    needs:
      - plugin
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v2
    - name: Upload release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        allow_override: true
        gzip: false
        tag: master
        name: master
        body: Build of ${{env.PLUGIN_NAME}} from master.
        files: >
          plugin/${{env.PLUGIN_NAME}}
